name: crokket
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22
  - pytorch=1.13
  - pytorch-cuda=11.6

  - pip:
    - numpy
    - scipy
    - pytest
    - matplotlib
    - transformers
    - git+https://github.com/openai/whisper.git
