name: crokket
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22
  - pytorch=1.13.1
  - pytorch-cuda=11.6
  - torchaudio=0.13.1
  - pip:
    - numpy==1.24.1
    - soundfile
    - pytest
    - matplotlib
    - transformers
    - pyyaml
