name: crocket
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip=22.2
  - pytorch
  - ffmpeg
  - onednn
  - pip:
    - numpy
    - scipy
    - pytest
    - matplotlib
    - transformers
    - git+https://github.com/openai/whisper.git
